# Generated by Django 2.1.3 on 2018-12-19 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата подачи заявки')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('finished', models.BooleanField(default=False, verbose_name='Выполнено')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('finished', models.BooleanField(default=False, verbose_name='Выполнено')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('finished', models.BooleanField(default=False, verbose_name='Выполнено')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='tracking_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания/建立日期')),
                ('name', models.CharField(max_length=128, verbose_name='Номер трека/快递单号码')),
                ('text', models.TextField(blank=True, verbose_name='Описание/简介')),
                ('finished', models.BooleanField(default=False, verbose_name='Получено в Китае/在中国收到')),
                ('finished1', models.BooleanField(default=False, verbose_name='Получено за рубежом/在国外收到')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
