# Generated by Django 2.1.3 on 2018-12-20 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-created_date', 'finished']},
        ),
        migrations.AlterModelOptions(
            name='knowledge',
            options={'ordering': ['-created_date', 'finished']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_date', 'finished']},
        ),
        migrations.AlterModelOptions(
            name='tracking_number',
            options={'ordering': ['-created_date', 'finished']},
        ),
    ]
