# Generated by Django 2.1.3 on 2018-12-20 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181220_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['finished', '-created_date']},
        ),
        migrations.AlterModelOptions(
            name='knowledge',
            options={'ordering': ['finished', '-created_date']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['finished', '-created_date']},
        ),
    ]
