# Generated by Django 2.1.3 on 2019-01-07 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181220_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='action',
            name='subcategory_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.action', verbose_name='Подзадача от'),
        ),
    ]
